//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicJournal.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudLess
    {
        public int ID_check { get; set; }
        public int ID_stud { get; set; }
        public int ID_less { get; set; }
        public int ID_dateless { get; set; }
        public Nullable<bool> Checkstat { get; set; }
    
        public virtual DateLesson DateLesson { get; set; }
        public virtual Lessons Lessons { get; set; }
        public virtual Students Students { get; set; }
    }
}
