//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicJournal.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int ID_user { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronic { get; set; }
        public Nullable<int> NumGroup { get; set; }
        public int ID_aut { get; set; }
    
        public virtual Autorization Autorization { get; set; }
    }
}
